apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: prod
spec:
  gateways:
  - prod-gateway
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: nginx-service.prod.svc.cluster.local
        port:
          number: 80 # Correct port number here (e.g., 80 for HTTP)
